import Link from "next/link";
import { AlertTriangle, ArrowUpRight, CloudOff, MonitorCheck, MoreHorizontal, Play, Radio, Upload } from "lucide-react";
import { PageHead } from "@/components/ui";
import { StatusPill } from "@/components/status-pill";
import { campaigns } from "@/data/mock";
export default function Dashboard(){return <><PageHead eyebrow="SEXTA-FEIRA, 28 DE AGOSTO" title="Operação em tempo real" description="Acompanhe a saúde da rede e o que está no ar agora." action={<button className="btn primary"><Play size={15}/> Nova campanha</button>}/>
 <section className="signal-strip"><div><span className="pulse-dot"/><small>TELAS CONECTADAS</small><strong>39 <em>/ 43</em></strong><p>90,7% da rede online</p></div><div><small>PRECISAM DE ATENÇÃO</small><strong>04</strong><p>2 offline · 2 com alerta</p></div><div><small>CONTEÚDOS HOJE</small><strong>184.290</strong><p className="up">↑ 8,4% desde ontem</p></div><div><small>CAMPANHAS NO AR</small><strong>12</strong><p>6 agendadas para hoje</p></div><div className="storage"><small>ARMAZENAMENTO</small><strong>684 GB <em>/ 1 TB</em></strong><span><i/></span><p>68% utilizado</p></div></section>
 <div className="dash-grid"><section className="panel network"><header><div><h2>Status da rede</h2><p>Disponibilidade nas últimas 24 horas</p></div><b>98,7%</b></header><div className="network-chart"><div className="bars">{[72,81,83,76,88,90,86,94,93,96,91,98,97,99,95,98,97,99,98,96,99,98,99,98].map((h,i)=><i key={i} style={{height:`${h}%`}} className={i===4||i===15?"bad":""}/>)}</div><div className="chart-label"><span>00h</span><span>06h</span><span>12h</span><span>18h</span><span>Agora</span></div></div><div className="status-row"><span><i className="green"/>Online <b>39</b></span><span><i className="red"/>Offline <b>2</b></span><span><i className="amber"/>Atenção <b>2</b></span><span><i className="grey"/>Sem sincronização <b>0</b></span></div></section>
 <section className="panel attention"><header><div><h2>Requer atenção</h2><p>Eventos que podem afetar a reprodução</p></div><Link href="/telas">Ver todas <ArrowUpRight size={13}/></Link></header><article><span className="alert-icon red"><CloudOff/></span><div><b>Vitrine Ala Norte</b><p>Offline — reprodução local ativa</p><small>Shopping Pátio Norte · há 3h</small></div><button><MoreHorizontal/></button></article><article><span className="alert-icon amber"><AlertTriangle/></span><div><b>Menu Digital Centro</b><p>Armazenamento em 91%</p><small>Sabor & Brasa Centro · há 28min</small></div><button><MoreHorizontal/></button></article></section></div>
 <section className="panel campaign-table"><header><div><h2>Campanhas em andamento</h2><p>Entrega e alcance das campanhas ativas</p></div><Link href="/campanhas">Todas as campanhas <ArrowUpRight size={13}/></Link></header><div className="data-wrap"><table className="data-table"><thead><tr><th>Campanha</th><th>Cliente</th><th>Período</th><th>Telas</th><th>Status</th><th>Progresso</th></tr></thead><tbody>{campaigns.slice(0,3).map(c=><tr key={c.id}><td><Link href={`/campanhas/${c.id}`}>{c.name}</Link></td><td>{c.client}</td><td>{c.start} — {c.end}</td><td>{c.screens}</td><td><StatusPill value={c.status}/></td><td><div className="progress-label"><span className="progress"><i style={{width:`${c.progress}%`}}/></span>{c.progress}%</div></td></tr>)}</tbody></table></div></section>
 <section className="activity"><header><h2>Atividade recente</h2><p>Atualizações de toda a operação</p></header><div><article><i><Radio/></i><span><b>Campanha publicada</b><p>Black Friday — Vale Sul entrou no ar em 24 telas</p></span><time>há 8 min</time></article><article><i><MonitorCheck/></i><span><b>Nova tela conectada</b><p>Totem Entrada Academia foi ativada por Lucas Mendes</p></span><time>há 31 min</time></article><article><i><Upload/></i><span><b>Novo material processado</b><p>menu-verao-vertical.webp está pronto para uso</p></span><time>há 1 h</time></article></div></section>
 </>}
