"use client";
import Link from "next/link";
import { Archive, ArrowLeft, Calendar, Check, ChevronRight, Download, FileVideo, Grid2X2, List, MapPin, MoreHorizontal, Plus, UploadCloud, X } from "lucide-react";
import { ChangeEvent, DragEvent, FormEvent, useRef, useState } from "react";
import { campaigns, clients, locations, media, screens } from "@/data/mock";
import { campaignSchema, clientSchema, FieldErrors, getFieldErrors, validateMediaFiles, validateMediaSignatures } from "@/lib/validation";
import { Button, Modal, PageHead, Toolbar } from "./ui";
import { StatusPill } from "./status-pill";
export function ClientsPage(){return <><PageHead eyebrow="RELACIONAMENTO" title="Clientes" description="Contas, campanhas e alcance de cada operação." action={<Modal title="Novo cliente" trigger={<Button><Plus size={15}/> Novo cliente</Button>}><Form fields={["Nome do responsável","Empresa","E-mail","Telefone"]}/></Modal>}/><Toolbar placeholder="Buscar cliente, empresa ou e-mail"/><Table heads={["Cliente","Contato","Status","Campanhas","Telas","Cadastro",""]} rows={clients.map(c=>[<Link href={`/clientes/${c.id}`}><b>{c.company}</b><span className="sub">{c.name}</span></Link>,<>{c.email}<span className="sub">{c.phone}</span></>,<StatusPill value={c.status}/>,c.campaigns,c.screens,c.since,<MoreHorizontal size={16}/>])}/></>}
export function ScreensPage(){return <><PageHead eyebrow="MONITORAMENTO" title="Telas" description="43 players em 18 locais · atualizado agora" action={<Button><Plus size={15}/> Adicionar tela</Button>}/><Toolbar placeholder="Buscar por nome, ID ou local"/><Table heads={["Tela / ID","Local","Grupo","Status","Conteúdo atual","Última sincronização","Resolução","Orientação"]} rows={screens.map(s=>[<Link href={`/telas/${s.id}`}><b>{s.name}</b><span className="sub">{s.code}</span></Link>,s.location,s.group,<StatusPill value={s.status}/>,s.content,s.sync,s.resolution,s.orientation])}/></>}
type CampaignFilter="Todas"|"Ativa"|"Agendada"|"Rascunho";
export function CampaignsPage(){
  const [filter,setFilter]=useState<CampaignFilter>("Todas");
  const [campaignItems,setCampaignItems]=useState(campaigns);
  const tabs:[CampaignFilter,string][]=[["Todas","Todas"],["Ativa","Ativas"],["Agendada","Agendadas"],["Rascunho","Rascunhos"]];
  const filtered=filter==="Todas"?campaignItems:campaignItems.filter((campaign)=>campaign.status===filter);
  function addCampaign(draft:CampaignDraft){const client=clients.find((item)=>item.id===draft.client);setCampaignItems((current)=>[...current,{id:`campanha-${Date.now()}`,name:draft.name,client:client?.company??"Cliente",status:"Rascunho",start:draft.start,end:draft.end,screens:draft.screens.length,progress:0}]);setFilter("Rascunho")}
  return <><PageHead eyebrow="DISTRIBUIÇÃO DE CONTEÚDO" title="Campanhas" description="Planeje, publique e acompanhe a entrega de conteúdo." action={<Modal title="Criar campanha" trigger={<Button><Plus size={15}/> Nova campanha</Button>}><CampaignWizard onCreate={addCampaign}/></Modal>}/><div className="tabs" role="tablist" aria-label="Filtrar campanhas">{tabs.map(([value,label])=><button type="button" role="tab" aria-selected={filter===value} className={filter===value?"active":""} onClick={()=>setFilter(value)} key={value}>{label} <em>{value==="Todas"?campaignItems.length:campaignItems.filter((campaign)=>campaign.status===value).length}</em></button>)}</div><Toolbar placeholder="Buscar campanhas"/><Table heads={["Campanha","Cliente","Status","Início","Fim","Telas","Entrega"]} rows={filtered.map(c=>[<Link href={`/campanhas/${c.id}`} key={c.id}>{c.name}</Link>,c.client,<StatusPill value={c.status}/>,c.start,c.end,c.screens,<div className="progress-label"><span className="progress"><i style={{width:`${c.progress}%`}}/></span>{c.progress}%</div>])}/></>
}
export function LocationsPage(){return <><PageHead eyebrow="INFRAESTRUTURA" title="Locais" description="Pontos físicos e telas instaladas em cada endereço." action={<Button><Plus size={15}/> Novo local</Button>}/><Toolbar placeholder="Buscar local, cidade ou cliente"/><Table heads={["Local","Cliente","Endereço","Cidade / UF","Telas","Status"]} rows={locations.map(l=>[<Link href={`/locais/${l.id}`}><b>{l.name}</b></Link>,l.client,l.address,`${l.city} / ${l.state}`,l.screens,<StatusPill value={l.status}/>])}/></>}
export function MediaPage(){return <><PageHead eyebrow="CONTEÚDO" title="Biblioteca de mídia" description="2.418 arquivos · 684 GB utilizados" action={<Modal title="Enviar novos arquivos" trigger={<Button><UploadCloud size={15}/> Enviar mídia</Button>}><MediaUpload/></Modal>}/><div className="media-tools"><Toolbar placeholder="Buscar arquivos"/><div className="view-toggle"><button type="button" className="active"><Grid2X2/></button><button type="button"><List/></button></div></div><div className="media-grid">{media.map(m=><article key={m.id}><div className="media-preview" style={{background:m.color}}><span>{m.type==="Vídeo"?<FileVideo/>:<div className="art-shape"/>}</span><em>{m.duration}</em></div><div className="media-meta"><b>{m.name}</b><span>{m.resolution} · {m.size}</span><footer><small>{m.client}</small><StatusPill value={m.status}/></footer></div></article>)}</div></>}
function MediaUpload(){
  const inputRef=useRef<HTMLInputElement>(null);
  const [files,setFiles]=useState<File[]>([]);
  const [errors,setErrors]=useState<string[]>([]);
  const [ready,setReady]=useState(false);
  function addFiles(incoming:File[]){
    const merged=[...files,...incoming].filter((file,index,list)=>list.findIndex((item)=>item.name===file.name&&item.size===file.size&&item.lastModified===file.lastModified)===index);
    setFiles(merged);
    setErrors(validateMediaFiles(merged));
    setReady(false);
  }
  function choose(event:ChangeEvent<HTMLInputElement>){addFiles(Array.from(event.target.files??[]));event.target.value=""}
  function drop(event:DragEvent<HTMLDivElement>){event.preventDefault();addFiles(Array.from(event.dataTransfer.files))}
  function remove(index:number){const next=files.filter((_,fileIndex)=>fileIndex!==index);setFiles(next);setErrors(next.length?validateMediaFiles(next):[]);setReady(false)}
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const basicErrors=validateMediaFiles(files);const signatureErrors=basicErrors.length?[]:await validateMediaSignatures(files);const validationErrors=[...basicErrors,...signatureErrors];setErrors(validationErrors);setReady(!validationErrors.length)}
  function size(bytes:number){if(bytes>=1024**3)return `${(bytes/1024**3).toFixed(2)} GB`;return `${(bytes/1024**2).toFixed(1)} MB`}
  return <form className="media-upload" onSubmit={submit} noValidate><div className="dropzone" onDragOver={(event)=>event.preventDefault()} onDrop={drop}><UploadCloud/><b>Arraste seus arquivos aqui</b><p>JPG, PNG ou WEBP: até 25 MB · MP4 ou WEBM: até 1 GB<br/>Máximo de 10 arquivos e 2 GB por envio</p><input ref={inputRef} type="file" accept=".jpg,.jpeg,.png,.webp,.mp4,.webm,image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple onChange={choose}/><Button secondary onClick={()=>inputRef.current?.click()}>Selecionar arquivos</Button></div>{files.length>0&&<div className="upload-list">{files.map((file,index)=><div key={`${file.name}-${file.lastModified}`}><FileVideo/><span><b>{file.name}</b><small>{file.type||"Formato desconhecido"} · {size(file.size)}</small></span><button type="button" className="icon-btn" onClick={()=>remove(index)} aria-label={`Remover ${file.name}`}><X size={15}/></button></div>)}</div>}{errors.length>0&&<div className="upload-errors" role="alert">{errors.map((error)=><p key={error}>{error}</p>)}</div>}{ready&&<p className="form-success" role="status">Arquivos validados e prontos para envio.</p>}<div className="modal-actions"><Button type="submit" disabled={!files.length}>Validar e enviar</Button></div></form>
}
function Table({heads,rows}:{heads:string[],rows:React.ReactNode[][]}){return <div className="data-wrap"><table className="data-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((cell,j)=><td data-label={heads[j]} key={j}>{cell}</td>)}</tr>)}</tbody></table><div className="pagination"><span>Mostrando {rows.length} resultados</span><span>Página 1 de 1</span></div></div>}
function FieldError({name,errors}:{name:string,errors:FieldErrors}){return errors[name]?<small className="field-error" role="alert">{errors[name]}</small>:null}
function Form({fields: _fields}:{fields:string[]}){
  const [errors,setErrors]=useState<FieldErrors>({});
  const [saved,setSaved]=useState(false);
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setSaved(false);const result=clientSchema.safeParse(Object.fromEntries(new FormData(event.currentTarget)));if(!result.success){setErrors(getFieldErrors(result.error));return}setErrors({});setSaved(true)}
  return <form className="modal-body" onSubmit={submit} noValidate><div className="field-grid"><label className="field">Nome do responsável<input name="contactName" type="text" placeholder="Digite o nome..." minLength={2} maxLength={100} autoComplete="name" required aria-invalid={!!errors.contactName}/><FieldError name="contactName" errors={errors}/></label><label className="field">Empresa<input name="company" type="text" minLength={2} maxLength={120} autoComplete="organization" required aria-invalid={!!errors.company}/><FieldError name="company" errors={errors}/></label><label className="field">E-mail<input name="email" type="email" inputMode="email" maxLength={254} autoComplete="email" required aria-invalid={!!errors.email}/><FieldError name="email" errors={errors}/></label><label className="field">Telefone<input name="phone" type="tel" inputMode="tel" placeholder="(11) 99999-9999" minLength={10} maxLength={20} autoComplete="tel" required aria-invalid={!!errors.phone}/><FieldError name="phone" errors={errors}/></label></div>{saved&&<p className="form-success" role="status">Dados validados com sucesso.</p>}<div className="modal-actions"><Button secondary>Cancelar</Button><Button type="submit">Salvar cliente</Button></div></form>
}
type CampaignDraft={name:string;client:string;objective:string;media:string;screens:string[];start:string;end:string};
function CampaignWizard({onCreate}:{onCreate:(draft:CampaignDraft)=>void}){
  const stages=["Informações","Mídias","Telas","Agendamento","Revisão"];
  const [step,setStep]=useState(0);
  const [errors,setErrors]=useState<FieldErrors>({});
  const [done,setDone]=useState(false);
  const [draft,setDraft]=useState<CampaignDraft>({name:"",client:"",objective:"",media:"",screens:[],start:"",end:""});
  function next(){
    const nextErrors:FieldErrors={};
    if(step===0){const result=campaignSchema.safeParse({name:draft.name,client:draft.client,objective:draft.objective});if(!result.success){setErrors(getFieldErrors(result.error));return}}
    if(step===1&&!draft.media)nextErrors.media="Selecione uma mídia.";
    if(step===2&&!draft.screens.length)nextErrors.screens="Selecione pelo menos uma tela.";
    if(step===3){if(!draft.start)nextErrors.start="Informe a data inicial.";if(!draft.end)nextErrors.end="Informe a data final.";if(draft.start&&draft.end&&draft.end<draft.start)nextErrors.end="A data final não pode ser anterior à inicial."}
    if(Object.keys(nextErrors).length){setErrors(nextErrors);return}
    setErrors({});setStep((current)=>Math.min(current+1,stages.length-1));
  }
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();if(step<stages.length-1){next();return}onCreate(draft);setDone(true)}
  function toggleScreen(id:string){setDraft((current)=>({...current,screens:current.screens.includes(id)?current.screens.filter((screen)=>screen!==id):[...current.screens,id]}))}
  return <form className="modal-body" onSubmit={submit} noValidate><div className="steps">{stages.map((stage,index)=><span className={index===step?"active":index<step?"complete":""} key={stage}><i>{index<step?<Check/>:index+1}</i>{stage}</span>)}</div>
    {done?<div className="wizard-result" role="status"><Check/><h3>Campanha criada com sucesso</h3><p>Ela foi salva e está pronta para publicação.</p></div>:<>
    {step===0&&<div className="field-grid"><label className="field">Nome da campanha<input value={draft.name} onChange={(event)=>setDraft({...draft,name:event.target.value})} type="text" placeholder="Ex.: Black Friday — Vale Sul" minLength={3} maxLength={120} required aria-invalid={!!errors.name}/><FieldError name="name" errors={errors}/></label><label className="field">Cliente<select value={draft.client} onChange={(event)=>setDraft({...draft,client:event.target.value})} required aria-invalid={!!errors.client}><option value="" disabled>Selecione um cliente</option>{clients.map((client)=><option value={client.id} key={client.id}>{client.company}</option>)}</select><FieldError name="client" errors={errors}/></label><label className="field">Objetivo<input value={draft.objective} onChange={(event)=>setDraft({...draft,objective:event.target.value})} type="text" placeholder="Descreva brevemente" minLength={3} maxLength={300} required aria-invalid={!!errors.objective}/><FieldError name="objective" errors={errors}/></label><label className="field">Responsável<input value="Lucas Mendes" maxLength={100} readOnly/></label></div>}
    {step===1&&<fieldset className="wizard-options"><legend>Selecione a mídia da campanha</legend>{media.map((item)=><label key={item.id}><input type="radio" name="media" value={item.id} checked={draft.media===item.id} onChange={()=>setDraft({...draft,media:item.id})}/><span><b>{item.name}</b><small>{item.type} · {item.resolution}</small></span></label>)}<FieldError name="media" errors={errors}/></fieldset>}
    {step===2&&<fieldset className="wizard-options"><legend>Selecione as telas</legend>{screens.map((screen)=><label key={screen.id}><input type="checkbox" value={screen.id} checked={draft.screens.includes(screen.id)} onChange={()=>toggleScreen(screen.id)}/><span><b>{screen.name}</b><small>{screen.location} · {screen.status}</small></span></label>)}<FieldError name="screens" errors={errors}/></fieldset>}
    {step===3&&<div className="field-grid"><label className="field">Data inicial<input type="date" value={draft.start} onChange={(event)=>setDraft({...draft,start:event.target.value})} required aria-invalid={!!errors.start}/><FieldError name="start" errors={errors}/></label><label className="field">Data final<input type="date" value={draft.end} min={draft.start||undefined} onChange={(event)=>setDraft({...draft,end:event.target.value})} required aria-invalid={!!errors.end}/><FieldError name="end" errors={errors}/></label></div>}
    {step===4&&<div className="wizard-review"><h3>Revise antes de criar</h3><dl><div><dt>Campanha</dt><dd>{draft.name}</dd></div><div><dt>Cliente</dt><dd>{clients.find((client)=>client.id===draft.client)?.company}</dd></div><div><dt>Mídia</dt><dd>{media.find((item)=>item.id===draft.media)?.name}</dd></div><div><dt>Telas</dt><dd>{draft.screens.length}</dd></div><div><dt>Período</dt><dd>{draft.start} até {draft.end}</dd></div></dl></div>}
    <div className="modal-actions">{step>0&&<Button secondary onClick={()=>{setErrors({});setStep((current)=>current-1)}}>Voltar</Button>}<Button type="submit">{step===stages.length-1?"Criar campanha":<>Continuar <ChevronRight size={14}/></>}</Button></div></>}
  </form>
}
export function DetailPage({type,id}:{type:string,id:string}){const item=type==="telas"?screens.find(x=>x.id===id):type==="clientes"?clients.find(x=>x.id===id):type==="locais"?locations.find(x=>x.id===id):campaigns.find(x=>x.id===id);if(!item)return <Empty/>;const name="name" in item?item.name:"Detalhes";return <><Link className="back" href={`/${type}`}><ArrowLeft/> Voltar para {type}</Link><PageHead eyebrow={type.toUpperCase()} title={name} description={type==="telas"?(item as typeof screens[0]).code:"Visão geral, atividade e informações relacionadas"} action={<><Button secondary><Archive size={14}/> Arquivar</Button> <Button>Editar</Button></>}/>{type==="telas"?<ScreenDetail screen={item as typeof screens[0]}/>:<GenericDetail type={type} item={item}/>}</>}
function ScreenDetail({screen}:{screen:typeof screens[0]}){return <><div className="monitor-grid"><section className="screen-stage"><div className="stage-head"><StatusPill value={screen.status}/><span>AO VIVO · ATUALIZADO AGORA</span></div><div className={`display ${screen.orientation==="Vertical"?"vertical":""}`}><div><small>EM REPRODUÇÃO</small><strong>{screen.content}</strong><span>00:18 / 00:30</span></div></div></section><section className="device-info"><h3>Estado do player</h3>{[["Player ID",screen.code],["Último heartbeat","há 18 segundos"],["Última sincronização",screen.sync],["Versão do player","v3.8.2"],["Armazenamento","18,4 GB disponíveis"],["Programação","v. 184 · sincronizada"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</section></div><div className="detail-tabs"><button className="active">Programação atual</button><button>Histórico de reproduções</button><button>Histórico de conexão</button></div><section className="timeline-list"><article><time>08:00 — 12:00</time><i/><div><b>Institucional Agosto</b><span>Loop de 4 materiais · 30 min</span></div><StatusPill value="Ativa"/></article><article><time>12:00 — 14:00</time><i/><div><b>Campanha Almoço Executivo</b><span>Agendada · 3 materiais</span></div><StatusPill value="Agendada"/></article></section></>}
function GenericDetail({type,item}:{type:string,item:object}){return <div className="detail-columns"><section className="info-sheet"><h3>Informações</h3>{Object.entries(item).slice(1).map(([k,v])=><div key={k}><span>{k}</span><b>{String(v)}</b></div>)}</section><section className="related"><h3>Atividade e itens relacionados</h3>{["Campanha Black Friday publicada","Nova mídia enviada para aprovação","Programação atualizada em 8 telas"].map((x,i)=><article key={x}><i>{i+1}</i><div><b>{x}</b><span>por Lucas Mendes · há {i+1} hora(s)</span></div></article>)}</section></div>}
function Empty(){return <div className="empty"><MapPin/><h2>Registro não encontrado</h2><p>Verifique o endereço e tente novamente.</p></div>}
