"use client";
import Link from "next/link";
import { Archive, ArrowLeft, Calendar, Check, ChevronRight, Download, FileVideo, Grid2X2, List, MapPin, MoreHorizontal, Plus, UploadCloud } from "lucide-react";
import { campaigns, clients, locations, media, screens } from "@/data/mock";
import { Button, Modal, PageHead, Toolbar } from "./ui";
import { StatusPill } from "./status-pill";
export function ClientsPage(){return <><PageHead eyebrow="RELACIONAMENTO" title="Clientes" description="Contas, campanhas e alcance de cada operação." action={<Modal title="Novo cliente" trigger={<Button><Plus size={15}/> Novo cliente</Button>}><Form fields={["Nome do responsável","Empresa","E-mail","Telefone"]}/></Modal>}/><Toolbar placeholder="Buscar cliente, empresa ou e-mail"/><Table heads={["Cliente","Contato","Status","Campanhas","Telas","Cadastro",""]} rows={clients.map(c=>[<Link href={`/clientes/${c.id}`}><b>{c.company}</b><span className="sub">{c.name}</span></Link>,<>{c.email}<span className="sub">{c.phone}</span></>,<StatusPill value={c.status}/>,c.campaigns,c.screens,c.since,<MoreHorizontal size={16}/>])}/></>}
export function ScreensPage(){return <><PageHead eyebrow="MONITORAMENTO" title="Telas" description="43 players em 18 locais · atualizado agora" action={<Button><Plus size={15}/> Adicionar tela</Button>}/><Toolbar placeholder="Buscar por nome, ID ou local"/><Table heads={["Tela / ID","Local","Grupo","Status","Conteúdo atual","Última sincronização","Resolução","Orientação"]} rows={screens.map(s=>[<Link href={`/telas/${s.id}`}><b>{s.name}</b><span className="sub">{s.code}</span></Link>,s.location,s.group,<StatusPill value={s.status}/>,s.content,s.sync,s.resolution,s.orientation])}/></>}
export function CampaignsPage(){return <><PageHead eyebrow="DISTRIBUIÇÃO DE CONTEÚDO" title="Campanhas" description="Planeje, publique e acompanhe a entrega de conteúdo." action={<Modal title="Criar campanha" trigger={<Button><Plus size={15}/> Nova campanha</Button>}><CampaignWizard/></Modal>}/><div className="tabs"><button className="active">Todas <em>24</em></button><button>Ativas <em>12</em></button><button>Agendadas <em>6</em></button><button>Rascunhos <em>3</em></button></div><Toolbar placeholder="Buscar campanhas"/><Table heads={["Campanha","Cliente","Status","Início","Fim","Telas","Entrega"]} rows={campaigns.map(c=>[<Link href={`/campanhas/${c.id}`}>{c.name}</Link>,c.client,<StatusPill value={c.status}/>,c.start,c.end,c.screens,<div className="progress-label"><span className="progress"><i style={{width:`${c.progress}%`}}/></span>{c.progress}%</div>])}/></>}
export function LocationsPage(){return <><PageHead eyebrow="INFRAESTRUTURA" title="Locais" description="Pontos físicos e telas instaladas em cada endereço." action={<Button><Plus size={15}/> Novo local</Button>}/><Toolbar placeholder="Buscar local, cidade ou cliente"/><Table heads={["Local","Cliente","Endereço","Cidade / UF","Telas","Status"]} rows={locations.map(l=>[<Link href={`/locais/${l.id}`}><b>{l.name}</b></Link>,l.client,l.address,`${l.city} / ${l.state}`,l.screens,<StatusPill value={l.status}/>])}/></>}
export function MediaPage(){return <><PageHead eyebrow="CONTEÚDO" title="Biblioteca de mídia" description="2.418 arquivos · 684 GB utilizados" action={<Modal title="Enviar novos arquivos" trigger={<Button><UploadCloud size={15}/> Enviar mídia</Button>}><div className="dropzone"><UploadCloud/><b>Arraste seus arquivos aqui</b><p>JPG, PNG, WEBP, MP4 ou WEBM · até 2 GB</p><Button secondary>Selecionar arquivos</Button></div></Modal>}/><div className="media-tools"><Toolbar placeholder="Buscar arquivos"/><div className="view-toggle"><button className="active"><Grid2X2/></button><button><List/></button></div></div><div className="media-grid">{media.map(m=><article key={m.id}><div className="media-preview" style={{background:m.color}}><span>{m.type==="Vídeo"?<FileVideo/>:<div className="art-shape"/>}</span><em>{m.duration}</em></div><div className="media-meta"><b>{m.name}</b><span>{m.resolution} · {m.size}</span><footer><small>{m.client}</small><StatusPill value={m.status}/></footer></div></article>)}</div></>}
function Table({heads,rows}:{heads:string[],rows:React.ReactNode[][]}){return <div className="data-wrap"><table className="data-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((cell,j)=><td data-label={heads[j]} key={j}>{cell}</td>)}</tr>)}</tbody></table><div className="pagination"><span>Mostrando {rows.length} resultados</span><span>Página 1 de 1</span></div></div>}
function Form({fields}:{fields:string[]}){return <div className="modal-body"><div className="field-grid">{fields.map((f,i)=><label className="field" key={f}>{f}<input placeholder={i===0?"Digite o nome...":""}/></label>)}</div><div className="modal-actions"><Button secondary>Cancelar</Button><Button>Salvar cliente</Button></div></div>}
function CampaignWizard(){return <div className="modal-body"><div className="steps">{["Informações","Mídias","Telas","Agendamento","Revisão"].map((s,i)=><span className={i===0?"active":""} key={s}><i>{i===0?1:<Check/>}</i>{s}</span>)}</div><div className="field-grid"><label className="field">Nome da campanha<input placeholder="Ex.: Black Friday — Vale Sul"/></label><label className="field">Cliente<select><option>Selecione um cliente</option><option>Grupo Aurora</option></select></label><label className="field">Objetivo<input placeholder="Descreva brevemente"/></label><label className="field">Responsável<input value="Lucas Mendes" readOnly/></label></div><div className="modal-actions"><Button secondary>Salvar rascunho</Button><Button>Continuar <ChevronRight size={14}/></Button></div></div>}
export function DetailPage({type,id}:{type:string,id:string}){const item=type==="telas"?screens.find(x=>x.id===id):type==="clientes"?clients.find(x=>x.id===id):type==="locais"?locations.find(x=>x.id===id):campaigns.find(x=>x.id===id);if(!item)return <Empty/>;const name="name" in item?item.name:"Detalhes";return <><Link className="back" href={`/${type}`}><ArrowLeft/> Voltar para {type}</Link><PageHead eyebrow={type.toUpperCase()} title={name} description={type==="telas"?(item as typeof screens[0]).code:"Visão geral, atividade e informações relacionadas"} action={<><Button secondary><Archive size={14}/> Arquivar</Button> <Button>Editar</Button></>}/>{type==="telas"?<ScreenDetail screen={item as typeof screens[0]}/>:<GenericDetail type={type} item={item}/>}</>}
function ScreenDetail({screen}:{screen:typeof screens[0]}){return <><div className="monitor-grid"><section className="screen-stage"><div className="stage-head"><StatusPill value={screen.status}/><span>AO VIVO · ATUALIZADO AGORA</span></div><div className={`display ${screen.orientation==="Vertical"?"vertical":""}`}><div><small>EM REPRODUÇÃO</small><strong>{screen.content}</strong><span>00:18 / 00:30</span></div></div></section><section className="device-info"><h3>Estado do player</h3>{[["Player ID",screen.code],["Último heartbeat","há 18 segundos"],["Última sincronização",screen.sync],["Versão do player","v3.8.2"],["Armazenamento","18,4 GB disponíveis"],["Programação","v. 184 · sincronizada"]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</section></div><div className="detail-tabs"><button className="active">Programação atual</button><button>Histórico de reproduções</button><button>Histórico de conexão</button></div><section className="timeline-list"><article><time>08:00 — 12:00</time><i/><div><b>Institucional Agosto</b><span>Loop de 4 materiais · 30 min</span></div><StatusPill value="Ativa"/></article><article><time>12:00 — 14:00</time><i/><div><b>Campanha Almoço Executivo</b><span>Agendada · 3 materiais</span></div><StatusPill value="Agendada"/></article></section></>}
function GenericDetail({type,item}:{type:string,item:object}){return <div className="detail-columns"><section className="info-sheet"><h3>Informações</h3>{Object.entries(item).slice(1).map(([k,v])=><div key={k}><span>{k}</span><b>{String(v)}</b></div>)}</section><section className="related"><h3>Atividade e itens relacionados</h3>{["Campanha Black Friday publicada","Nova mídia enviada para aprovação","Programação atualizada em 8 telas"].map((x,i)=><article key={x}><i>{i+1}</i><div><b>{x}</b><span>por Lucas Mendes · há {i+1} hora(s)</span></div></article>)}</section></div>}
function Empty(){return <div className="empty"><MapPin/><h2>Registro não encontrado</h2><p>Verifique o endereço e tente novamente.</p></div>}
