import { BarChart3, Download, Plus, Shield, Users, Monitor, Building2, Megaphone, PlaySquare, Settings, Bell, Plug, HardDrive } from "lucide-react";
import { Button, PageHead, SelectButton, Toolbar } from "./ui";
import { StatusPill } from "./status-pill";
const groupRows=[["Todas as lojas","43","18 locais","12 campanhas","Online"],["Shopping Centers","21","4 locais","6 campanhas","Online"],["Academias","8","3 locais","2 campanhas","Atenção"],["Recepções","6","5 locais","3 campanhas","Online"]];
const logRows=[["28/08/2026 · 14:32:08","Black Friday — Vale Sul","black-friday-praca-30s.mp4","Painel Praça de Alimentação","Shopping Vale Sul","Grupo Aurora","00:30","Confirmada"],["28/08/2026 · 14:31:42","Institucional Agosto","institucional-horizonte.mp4","Recepção Principal","Edifício Aurora","Rede Horizonte","00:20","Confirmada"],["28/08/2026 · 14:30:11","Menu de Verão","menu-verao-vertical.webp","Menu Digital Centro","Sabor & Brasa Centro","Sabor & Brasa","00:15","Pendente"]];
export function Groups(){return <ListPage eyebrow="ORGANIZAÇÃO DA REDE" title="Grupos de telas" desc="Distribua conteúdo para conjuntos de telas com uma única ação." button="Novo grupo" heads={["Grupo","Telas","Abrangência","Campanhas","Status"]} rows={groupRows}/>}
export function Playbacks(){return <ListPage eyebrow="AUDITORIA DE ENTREGA" title="Log de exibições" desc="Comprovantes de reprodução recebidos dos players." button="Exportar CSV" heads={["Data e horário","Campanha","Mídia","Tela","Local","Cliente","Duração","Status"]} rows={logRows}/>}
function ListPage({eyebrow,title,desc,button,heads,rows}:{eyebrow:string,title:string,desc:string,button:string,heads:string[],rows:string[][]}){return <><PageHead eyebrow={eyebrow} title={title} description={desc} action={<Button>{button.includes("Export")?<Download size={14}/>:<Plus size={14}/>} {button}</Button>}/><Toolbar/><div className="data-wrap"><table className="data-table"><thead><tr>{heads.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td data-label={heads[j]} key={j}>{j===0?<b>{x}</b>:j===r.length-1?<StatusPill value={x}/>:x}</td>)}</tr>)}</tbody></table></div></>}
export function Reports(){return <><PageHead eyebrow="ANÁLISE DE PERFORMANCE" title="Relatórios" description="Resultados de entrega e disponibilidade da sua rede." action={<Button><Download size={14}/> Exportar relatório</Button>}/><div className="report-filter"><SelectButton label="Todos os clientes"/><SelectButton label="Todas as campanhas"/><SelectButton label="24 — 30 de agosto"/><Button>Aplicar filtros</Button></div><div className="report-metrics"><div><span>EXIBIÇÕES NO PERÍODO</span><b>1.284.920</b><small>↑ 12,8% vs. período anterior</small></div><div><span>TEMPO TOTAL EXIBIDO</span><b>8.924 h</b><small>43 telas utilizadas</small></div><div><span>DISPONIBILIDADE</span><b>98,7%</b><small>Meta operacional: 98%</small></div></div><div className="report-grid"><section><h3>Exibições por dia</h3><div className="big-chart">{[60,78,66,84,72,91,86,96,75,87,94,81,97,91].map((h,i)=><i key={i} style={{height:`${h}%`}}/>)}</div><footer><span>17 ago</span><span>24 ago</span><span>Hoje</span></footer></section><section><h3>Distribuição por campanha</h3>{[["Black Friday — Vale Sul",72],["Institucional Agosto",54],["Menu de Verão",38],["Outras campanhas",21]].map(([x,n])=><div className="rank" key={x}><span>{x}</span><b>{n}%</b><i><em style={{width:`${n}%`}}/></i></div>)}</section></div></>}
export function UsersPage({advertisers=false}:{advertisers?:boolean}){return <><PageHead eyebrow="ACESSO E PERMISSÕES" title={advertisers?"Anunciantes":"Usuários"} description={advertisers?"Contas externas e acesso segregado por cliente.":"Equipe, funções e acesso à plataforma."} action={<Button><Plus size={14}/> {advertisers?"Novo anunciante":"Convidar usuário"}</Button>}/><Toolbar/><div className="user-list">{[["Lucas Mendes","lucas@signa.media","ADMINISTRADOR","LM"],["Ana Freitas","ana@signa.media","OPERADOR","AF"],["Marina Costa","marina@grupoaurora.com.br","CLIENTE","MC"]].map(u=><article key={u[1]}><i>{u[3]}</i><div><b>{u[0]}</b><span>{u[1]}</span></div><em>{u[2]}</em><StatusPill value="Ativo"/></article>)}</div></>}
export function SettingsPage(){const items=[[Settings,"Geral","Identidade, idioma e preferências"],[Users,"Usuários","Equipe e convites"],[Shield,"Permissões","Papéis e políticas de acesso"],[HardDrive,"Armazenamento","Uso, limites e retenção"],[Monitor,"Players","Versões e atualização remota"],[Bell,"Notificações","Alertas e canais de entrega"],[Plug,"Integrações","APIs e serviços conectados"],[Shield,"Segurança","Sessões e autenticação"]] as const;return <><PageHead eyebrow="ADMINISTRAÇÃO" title="Configurações" description="Preferências globais da organização e da rede."/><div className="settings-grid">{items.map(([Icon,t,d])=><button key={t}><Icon/><span><b>{t}</b><small>{d}</small></span></button>)}</div></>}
export function Portal(){return <div className="portal"><div className="portal-hero"><span>PORTAL DO ANUNCIANTE</span><h1>Boa tarde, Marina.</h1><p>Suas campanhas alcançaram 184 mil exibições esta semana.</p></div><div className="portal-metrics"><div><b>3</b><span>Campanhas ativas</span></div><div><b>24</b><span>Telas em exibição</span></div><div><b>98,9%</b><span>Entrega confirmada</span></div></div><section className="portal-campaign"><header><h2>Suas campanhas</h2><Button><Plus size={14}/> Enviar material</Button></header>{["Black Friday — Vale Sul","Institucional Grupo Aurora","Lançamento Primavera"].map((x,i)=><article key={x}><div className="portal-thumb"><Megaphone/></div><div><b>{x}</b><span>{i===2?"Aguardando aprovação":"Em exibição em 24 telas"}</span></div><StatusPill value={i===2?"Em revisão":"Ativa"}/></article>)}</section></div>}
